In [1]:
#imported numpy as np
import numpy as np

In [2]:
#created 1d array
arr_1d = np.array([1,2,3,4,5])
print(arr_1d)

[1 2 3 4 5]


In [3]:
#we wanted to know the type
type(arr_1d)

numpy.ndarray

In [4]:
#we wanted to know the dimension
arr_1d.ndim

1

In [6]:
#we created to 2d array
arr_2d = np.array([[1,2,3,4],[5,6,7,8]])
print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [7]:
#we wanted to know the dimension
arr_2d.ndim

2

In [9]:
#we wanted to know the size i.e. total number of elements
arr_1d.size

5

In [10]:
#we wanted to know the size i.e. total number of elements
arr_2d.size

8

In [11]:
#we wanted to know the shape of array which is given out as tuple
arr_1d.shape

(5,)

In [12]:
#we wanted to know the shape of array i.e. given in rows & columns
arr_2d.shape

(2, 4)

In [13]:
#we want to know the data type
arr_1d.dtype

dtype('int32')

In [14]:
#int32 means data type is integer represented in 32 bit format.
arr_2d.dtype

dtype('int32')